%% Call below command to convert .mmd to .png
%%  Adjust -w or -H if necessary
%% mmdc -p puppeteer-config.json -i after_compress_nodebasededge.mmd -o after_compress_nodebasededge.mmd.png

%%```mermaid
graph LR
Title[<u>After Compress NodeBasedEdge</u>]
Title --- Node1(( ))
style Title fill:#FFF,stroke:#FFF
linkStyle 0 stroke:#FFF,stroke-width:0;

Node1 -- 10+15+2 = 27s --- Node3(( ))
Node3 -- 15+10 = 25s  --- Node5(( ))

Node3 --- Node7(( ))


%%```